/// Weather impact on bike demand per neighbourhood per hour. Quantifies how weather conditions suppress or boost cycling demand.
table fact_weather_impact
	lineageTag: 1000000a-0001-0001-0001-000000000001
	sourceLineageTag: [fact_weather_impact]

	/// Total weather-adjusted demand across all hours and neighbourhoods
	measure 'Total Weather-Adjusted Demand' = SUM(fact_weather_impact[weather_adjusted_demand])
		formatString: #,##0
		lineageTag: 1000000a-0001-0001-0001-000000000101

	/// Average weather demand impact factor (1.0 = neutral, <1 = suppressed)
	measure 'Avg Weather Impact Factor' = AVERAGE(fact_weather_impact[weather_demand_impact])
		formatString: 0.00
		lineageTag: 1000000a-0001-0001-0001-000000000102

	/// Total demand gap: raw demand minus weather-adjusted demand
	measure 'Total Demand Gap' = SUM(fact_weather_impact[demand_gap])
		formatString: #,##0.0
		lineageTag: 1000000a-0001-0001-0001-000000000103

	/// Average cycling comfort index across all impact observations
	measure 'Avg Impact Comfort Index' = AVERAGE(fact_weather_impact[cycling_comfort_index])
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000104

	/// Hours with severe or moderate demand suppression (<0.7 impact factor)
	measure 'Suppressed Demand Hours' =
			CALCULATE(
			    COUNTROWS(fact_weather_impact),
			    fact_weather_impact[weather_demand_impact] < 0.7
			)
		formatString: #,##0
		lineageTag: 1000000a-0001-0001-0001-000000000105

	/// Percentage of hours where weather significantly suppresses demand
	measure 'Weather Suppression %' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_weather_impact),
			        fact_weather_impact[weather_demand_impact] < 0.7
			    ),
			    COUNTROWS(fact_weather_impact)
			) * 100
		formatString: 0.0"%"
		lineageTag: 1000000a-0001-0001-0001-000000000106

	/// Average temperature during demand observations
	measure 'Avg Demand Temperature °C' = AVERAGE(fact_weather_impact[temperature_c])
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000107

	/// Total raw demand events across all weather-impact observations
	measure 'Total Raw Demand Events' = SUM(fact_weather_impact[event_count])
		formatString: #,##0
		lineageTag: 1000000a-0001-0001-0001-000000000108

	column weather_impact_key
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-000000000011
		sourceLineageTag: weather_impact_key
		summarizeBy: none
		sourceColumn: weather_impact_key

		annotation SummarizationSetBy = Automatic

	column weather_key
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-000000000012
		sourceLineageTag: weather_key
		summarizeBy: none
		sourceColumn: weather_key

		annotation SummarizationSetBy = Automatic

	column neighbourhood_key
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-000000000013
		sourceLineageTag: neighbourhood_key
		summarizeBy: none
		sourceColumn: neighbourhood_key

		annotation SummarizationSetBy = Automatic

	column time_key
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-000000000014
		sourceLineageTag: time_key
		summarizeBy: none
		sourceColumn: time_key

		annotation SummarizationSetBy = Automatic

	column event_hour
		dataType: dateTime
		formatString: General Date
		lineageTag: 1000000a-0001-0001-0001-000000000015
		sourceLineageTag: event_hour
		summarizeBy: none
		sourceColumn: event_hour

		annotation SummarizationSetBy = Automatic

	column impact_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1000000a-0001-0001-0001-000000000016
		sourceLineageTag: impact_date
		summarizeBy: none
		sourceColumn: impact_date

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-000000000030
		sourceLineageTag: date_key
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 1000000a-0001-0001-0001-000000000017
		sourceLineageTag: neighbourhood
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column event_count
		dataType: int64
		formatString: #,##0
		lineageTag: 1000000a-0001-0001-0001-000000000018
		sourceLineageTag: event_count
		summarizeBy: sum
		sourceColumn: event_count

		annotation SummarizationSetBy = Automatic

	column weather_adjusted_demand
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000019
		sourceLineageTag: weather_adjusted_demand
		summarizeBy: sum
		sourceColumn: weather_adjusted_demand

		annotation SummarizationSetBy = Automatic

	column weather_demand_impact
		dataType: double
		formatString: 0.00
		lineageTag: 1000000a-0001-0001-0001-00000000001a
		sourceLineageTag: weather_demand_impact
		summarizeBy: average
		sourceColumn: weather_demand_impact

		annotation SummarizationSetBy = Automatic

	column temperature_c
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-00000000001b
		sourceLineageTag: temperature_c
		summarizeBy: average
		sourceColumn: temperature_c

		annotation SummarizationSetBy = Automatic

	column feels_like_c
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-00000000001c
		sourceLineageTag: feels_like_c
		summarizeBy: average
		sourceColumn: feels_like_c

		annotation SummarizationSetBy = Automatic

	column wind_speed_kmh
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-00000000001d
		sourceLineageTag: wind_speed_kmh
		summarizeBy: average
		sourceColumn: wind_speed_kmh

		annotation SummarizationSetBy = Automatic

	column has_precipitation
		dataType: boolean
		formatString: &quot;TRUE&quot;;&quot;TRUE&quot;;&quot;FALSE&quot;
		lineageTag: 1000000a-0001-0001-0001-00000000001e
		sourceLineageTag: has_precipitation
		summarizeBy: none
		sourceColumn: has_precipitation

		annotation SummarizationSetBy = Automatic

	column cloud_cover_pct
		dataType: int64
		formatString: 0
		lineageTag: 1000000a-0001-0001-0001-00000000001f
		sourceLineageTag: cloud_cover_pct
		summarizeBy: average
		sourceColumn: cloud_cover_pct

		annotation SummarizationSetBy = Automatic

	column cycling_comfort_index
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000020
		sourceLineageTag: cycling_comfort_index
		summarizeBy: average
		sourceColumn: cycling_comfort_index

		annotation SummarizationSetBy = Automatic

	column weather_severity
		dataType: string
		lineageTag: 1000000a-0001-0001-0001-000000000021
		sourceLineageTag: weather_severity
		summarizeBy: none
		sourceColumn: weather_severity

		annotation SummarizationSetBy = Automatic

	column weather_category
		dataType: string
		lineageTag: 1000000a-0001-0001-0001-000000000022
		sourceLineageTag: weather_category
		summarizeBy: none
		sourceColumn: weather_category

		annotation SummarizationSetBy = Automatic

	column weather_description
		dataType: string
		lineageTag: 1000000a-0001-0001-0001-000000000023
		sourceLineageTag: weather_description
		summarizeBy: none
		sourceColumn: weather_description

		annotation SummarizationSetBy = Automatic

	column visibility_km
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000024
		sourceLineageTag: visibility_km
		summarizeBy: average
		sourceColumn: visibility_km

		annotation SummarizationSetBy = Automatic

	column impact_category
		dataType: string
		lineageTag: 1000000a-0001-0001-0001-000000000025
		sourceLineageTag: impact_category
		summarizeBy: none
		sourceColumn: impact_category

		annotation SummarizationSetBy = Automatic

	column demand_gap
		dataType: double
		formatString: 0.0
		lineageTag: 1000000a-0001-0001-0001-000000000026
		sourceLineageTag: demand_gap
		summarizeBy: sum
		sourceColumn: demand_gap

		annotation SummarizationSetBy = Automatic

	column loaded_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 1000000a-0001-0001-0001-000000000027
		sourceLineageTag: loaded_at
		summarizeBy: none
		sourceColumn: loaded_at

		annotation SummarizationSetBy = Automatic

	partition fact_weather_impact = entity
		mode: directLake
		source
			entityName: fact_weather_impact
			expressionSource: 'DirectLake - bicycles_gold'
